cc_binary(
    name = "run_games",
    srcs = ["run_games.cc"],
    linkopts = ["-lprofiler"],
    deps = [
        "@com_google_absl//absl/flags:parse",
        "@com_google_absl//absl/log:flags",
    ],
)
