package(default_visibility = ["//visibility:public"])

cc_library(
    name = "random",
    srcs = ["random.cc"],
    hdrs = ["random.h"],
    deps = [
        "//game:player",
        "@abseil-cpp//absl/log:check",
    ],
)
